kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chaos-lab
spec:
  selector:
    app: backend
  ports:
    - port: 5678
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chaos-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:0.2.3
          args:
            - "-text=hello from backend"
            - "-listen=:5678"
          ports:
            - containerPort: 5678